### PR TITLE
Add missing 17xy tags and fix some in posts

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add missing 17xy tags (and fix some in posts). They are used in all release posts but lead to 404 pages although being featured in pages like https://build.prestashop.com/news/prestashop-1-7-6-9-maintenance-release/
| Fixed ticket? |

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @matks

**Comment by ttoine** [comment]
did you created the tags in the data too ?
https://github.com/PrestaShop/prestashop.github.io/blob/master/_data/tags.yml

**Comment by matks** [comment]
> did you created the tags in the data too ?
> https://github.com/PrestaShop/prestashop.github.io/blob/master/_data/tags.yml

No, I did not. No idea what it does.

**Comment by ttoine** [comment]
for what I understand, during the generation of the website, it builds the list of articles with the tag. however, not sure how it works.

**Pull request merged**
