### PR TITLE
Migrate Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Migrate Travis CI to GitHub Actions
| Fixed ticket? | N/A

:green_circle: GA is green : https://github.com/Progi1984/prestashop.github.io/actions/runs/580959726

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Comment by matks** [comment]
@Progi1984 Are you able to verify the switch from Travis to GA works correctly with the deployment capability of GitHub Pages?

**Comment by Progi1984** [comment]
@matks It's the same used in https://github.com/PrestaShop/test-scenarios every day.

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @Progi1984 
Let's take the risk and improve if needed :)

**Comment by matks** [comment]
> Thank you @Progi1984
> Let's take the risk and improve if needed :)

We'll see if it works on Monday when we publish the Core Weekly 😄

**Comment by matks** [comment]
I dont know if it's relevant, but the GA failed on my fork because there is no API key for Algolia.

https://github.com/matks/prestashop.github.io/runs/1982935936?check_suite_focus=true
```

59s
0s
1s
Run bundle exec jekyll algolia push
Configuration file: /home/runner/work/prestashop.github.io/prestashop.github.io/_config.yml
[✗ Error] Missing API key                                                        
                                                                                 
The jekyll-algolia plugin could not find your API key.                           
                                                                                 
Please, define your API key either by:                                           
                                                                                 
1/ Defining an ENV variable when calling `jekyll algolia`                        
   $ ALGOLIA_API_KEY='your_api_key' jekyll algolia                               
                                                                                 
2/ Save your API key in a named `_algolia_api_key` in your source directory.     
   If you do this, we strongly recommend you to NOT track this file in your      
versionning system.   
```

This key might have been set a secret in Travis? 🤔

**Comment by matks** [comment]
Same for this repo
https://github.com/PrestaShop/prestashop.github.io/runs/1981311241?check_suite_focus=true

**Pull request merged**
