### PR TITLE
Move 1.7.6.9 release note to the right folder

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The release note should have been posted on the `releases` folder. This PR fixes it.

### CODE REVIEW

**Comment by matks** [comment]
We need to be sure this will not break some links. We dont want to break SEO, especially on something important like this 😅

**Review by Progi1984 — APPROVED** [review]

**Comment by atomiix** [comment]
@matks how can we make sure? By doing it locally?

**Comment by matks** [comment]
> @matks how can we make sure? By doing it locally?

Yes 👍  what we need to be sure is that "moving the file from one folder to another" does not change its URL.

README contains instructions to build locally but be prepared: it's very sloooooooooow

**Comment by ttoine** [comment]
links are always the same structure:
https://build.prestashop.com/news/prestashop-1-7-6-7-maintenance-release/
https://build.prestashop.com/news/prestashop-1-7-6-5-maintenance-release/
https://build.prestashop.com/news/prestashop-1-7-7-0-rc-release/
https://build.prestashop.com/news/do-you-speak-prestashop-october-2020/
https://build.prestashop.com/news/coreweekly-45-2020/
no matter what folder you are using.

**Comment by atomiix** [comment]
@matks just checked locally and everything is working well 👍

**Review by sowbiba — APPROVED** [review]

**Comment by matks** [comment]
Thank you @atomiix

**Pull request merged**
