### PR TITLE
Fix date

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by PrestaEdit** [comment]
https://github.com/PrestaShop/prestashop.github.io/commit/bdf248a109aa2e7e5219c1fee3930669ee159ad9

**Comment by Quetzacoalt91** [comment]
Nice catch, but it seems @xBorderie already fixed the date. :laughing:

**Comment by xBorderie** [comment]
Ca vaaaaaaaaaaaaaaaa ;)

**Comment by PrestaEdit** [comment]
;-)

**Pull request closed without merging**
