### PR TITLE
Publish Crowdin Monthly September 2022

### PR DESCRIPTION
**Pull request by l-delin**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Review by matks — COMMENTED** [review]
@l-delin Content is OK. Do we wait for @Julievrz approval?

Don't forget to update date when ready for publication. Please ping me for merge on publication date

**Comment by Julievrz** [comment]
Hi @matks, Léa is at school all week. I thought this had already been published. It can be published today, I have already reviewed it. :) Thank you!

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
@kpodemski Merged just before 10am 😆 I dont know if this is going to be published

**Comment by kpodemski** [comment]
@matks yeah, I didn't notice the hour

Next time, if we publish one article a day, I suggest removing the hour 👍

**Comment by Julievrz** [comment]
> @matks yeah, I didn't notice the hour
> 
> Next time, if we publish one article a day, I suggest removing the hour 👍

This is tricky because the other day we didn't specify the hour and the article wasn't published. 😅 
Wait and see haha, thank you!

**Pull request merged**
