### PR TITLE
Added back spaces before colons, looks better in this case

### PR DESCRIPTION
**Pull request by djfm**

### CODE REVIEW

**Comment by xBorderie** [comment]
It's not even a question of looking better: it's a rule of English typography :)

**Comment by djfm** [comment]
Err, not exactly :) http://en.wikipedia.org/wiki/Colon_%28punctuation%29#Spacing

**Comment by xBorderie** [comment]
@djfm, are you referring to "In print, a thin space is traditionally placed before a colon and a thick space after it", or to "In modern English-language printing, no space is placed before a colon and a single space is placed after it"?

**Comment by djfm** [comment]
Sorry yes this one: "In modern English-language printing, no space is placed before a colon and a single space is placed after it."

**Pull request merged**
