### PR TITLE
Enable Meta tags for Twitter

### PR DESCRIPTION
**Pull request by matks**
The Build articles are very often being shared on media such as Twitter (see [example](https://twitter.com/PrestaShop/status/1275425195067691008)) or LinkedIn. We could very easily improve the displays of Build articles by enabling the right meta tags for Build blog.

I start here with our Core Weekly articles. I followed [Twitter guidelines for meta tags](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image) and enabled the use of dedicated meta tags for Twitter when a `twitter_image` property is defined for one page.
```
twitter_image: /assets/images/theme/banner-core-weekly.jpg
```

My end goal is to deliver beautiful Twitter cards like [dev.to](dev.to) does:
Capture d’écran 2020-07-12 à 15 13 13

Although I tried to follow Twitter guidelines as much as possible, I am not sure how to test the end result without merging this PR and deploying it in production 🤔  . [This tool from Twitter](https://cards-dev.twitter.com/validator) allows to preview how a specific page would be displayed inside Twitter, but it requires a resource online.

And I don't want to host a copy of the blog on my website 😅

### CODE REVIEW

**Comment by matks** [comment]
I started exploring the code of dev.to to understand how they build their Twitter image cards.
If I'm not wrong, they render the image as HTML then use https://hcti.io/ to convert it to image and finally store it on https://cloudinary.com/

**Comment by matks** [comment]
> I started exploring the code of dev.to to understand how they build their Twitter image cards.
> If I'm not wrong, they render the image as HTML then use https://hcti.io/ to convert it to image and finally store it on https://cloudinary.com/

So if I want to achieve something similar, I need to deliver the following milestones as Pull Requests:
1. generate an HTML page with the desired display for each Build article

Example:



2. make Jeckyll call https://hcti.io/ API to obtain an image (free plan provides 50 images / months)
3. store image somewhere, maybe on https://cloudinary.com/ (free plan provides 25 credits = 25 GB)
4. serve constructed image through the right meta tags

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
Thank you for review

**Comment by matks** [comment]
According to https://build.prestashop.com/news/coreweekly-27-2020/ this is a failure 😞  it does not recognize it

**Comment by matks** [comment]
> According to https://build.prestashop.com/news/coreweekly-27-2020/ this is a failure 😞 it does not recognize it

Maybe the image path is wrong. 
```
<meta name="twitter:image" content="/assets/images/theme/banner-core-weekly.jpg">
```
⬇️ 
```
<meta name="twitter:image" content="https://build.prestashop.com/assets/images/theme/banner-core-weekly.jpg">
```

**Comment by ttoine** [comment]
Samuel and I added some meta picture in the head of Build articles. So you have working examples, for releases and a few other contents.

**Pull request merged**
