### PR TITLE
#typo

### PR DESCRIPTION
**Pull request by panploenes**

### CODE REVIEW

**Comment by panploenes** [comment]
Hopefully now then :)

EDIT: Maybe consider changing the link itself to be correct aswell "1.6.1.0" instead of "1.6.0.1" but i guess you gonna have to change all hrefs you did  with the link.

**Comment by xBorderie** [comment]
Perfect, thanks!

**Comment by xBorderie** [comment]
@julienbourdeau, can you regenerate the site? :)

**Comment by xBorderie** [comment]
Indeed, the version in the URL is wrong! I did not notice that! @julienbourdeau, can you see about it?

**Comment by julienbourdeau** [comment]
Hi,

I fixed the link https://github.com/PrestaShop/build.prestashop.com/commit/84e727ff9474c67da0cbfe5efdd97a7e99242414 and it's now live.

Sorry for the delay and thanks @panploenes :)

**Pull request merged**
