### PR TITLE
[-] Update CSS / Fix the size of the contributor image.

### PR DESCRIPTION
**Pull request by PrestaEdit**
(It will be prettyer like that)

### CODE REVIEW

**Comment by PrestaEdit** [comment]
ping @julienbourdeau

**Comment by PrestaEdit** [comment]
Ok , you fix it.

**Comment by julienbourdeau** [comment]
Hi,

Sorry but I couldn't get this to work locally so I used `push -f` to fix things as I see them... :sweat_smile:
Thank you tho

**Comment by PrestaEdit** [comment]
:stuck_out_tongue:

**Pull request closed without merging**
