### PR TITLE
Create do-you-speak-prestashop-july-2023.md

### PR DESCRIPTION
**Pull request by l-delin**
Here's the DYSP for July 2023 🗞

### CODE REVIEW

**Comment by l-delin** [comment]
Ping @coffrep and @kpodemski for review 🏋️

**Review by Julievrz — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]
We'll merge on 21st :)

**Comment by l-delin** [comment]
Perfect, thank you @kpodemski :-)

**Comment by matks** [comment]
It's the 21st 😄 @l-delin @kpodemski

**Comment by kpodemski** [comment]
thanks @matks :D

**Comment by l-delin** [comment]
Thanks! 🎉

**Pull request merged**
