### PR TITLE
Updated the article considered the decision to remove the assets

### PR DESCRIPTION
**Pull request by sam-pires**
- Removed the alert in the first paragraph
- Added an EDIT with the decision in the intro
- Adapted the bottom alert so it makes sense after the 2 first modifications
 

Still need to check if the EDIT content is pertinent and correct.

### CODE REVIEW

**Comment by sam-pires** [comment]
Hello @PierreRambaud, 

Could you check if the EDIT at the top of the article is complete and correct? Feel free to add stuff.

BTW, is the doc updated with all the info?
We should wait for it to be updated before merging this PR

**Review by ttoine — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@sam-pires Thanks, it's ok for me :+1:

**Comment by ttoine** [comment]
can we merge it then ?

**Comment by sam-pires** [comment]
Let's merge!

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @sam-pires

**Pull request merged**
