### PR TITLE
[DON'T MERGE]Delete the Jekyll default canonical tag

### LINKED ISSUE #569: Build blog has 2 identical canonical tag in the header
image012

As you can see, the "canonical" tag is generated twice. We need to find why it is duplicated and then, remove the second one.

### PR DESCRIPTION
**Pull request by sam-pires**
Fix #569 

Deleted the line generating the Jekyll canonical, there is now only one, generated by the jekyll-seo-tag plugin.

Ran locally:
Capture d’écran 2020-01-25 à 14 51 34

### CODE REVIEW

**Comment by sam-pires** [comment]
PR available @ttoine

**Comment by ttoine** [comment]
why ".gitignore" has been modified?
also @eternoendless can you please check on your side? I prefer that you have a look when it touches the template.

**Comment by sam-pires** [comment]
Sure, I always expect (and want) a review anyway 🙂 

I modified the .gitignore file to not track the Ruby version. 
Let me know if it is not recommended to add it to the .gitignore

**Comment by matks** [comment]
`.gitignore` content is fine (adding or not `.ruby-version` file is a debate, there is no single answer) and harmless

**Comment by sam-pires** [comment]
I screwed my PR, I close it and create new one.

**Pull request closed without merging**
