### PR TITLE
Publish Crowdin monthly December 2021

### PR DESCRIPTION
**Pull request by Julievrz**
Publish Crowdin monthly December 2021

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]
Is it normal to have hidden unicode characters? 
image

**Comment by Julievrz** [comment]
> Is it normal to have hidden unicode characters? image

I don't know, I assumed it was because of Daniel Shapiro's name that was in Hebrew. 🤔 What should I do about it? I think there were Unicode characters in my previous Crowdin monthly but we couldn't see them.

**Comment by Julievrz** [comment]
Please don't merge the article now. I'd like to add a paragraph to inform translators about the catalog push (Emailsalert module)

**Comment by atomiix** [comment]
@Julievrz there's also hidden unicode characters [line 71](https://github.com/PrestaShop/prestashop.github.io/pull/1016/files#diff-5c4cb57f549657a9dbdc74834e4db27567d8cbfebee4b190b20f21071ade6560R71) I think we should get rid of them if it doesn't have impact on the final text?

**Comment by Julievrz** [comment]
> @Julievrz there's also hidden unicode characters [line 71](https://github.com/PrestaShop/prestashop.github.io/pull/1016/files#diff-5c4cb57f549657a9dbdc74834e4db27567d8cbfebee4b190b20f21071ade6560R71) I think we should get rid of them if it doesn't have impact on the final text?

It should be ok

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @Julievrz

**Pull request merged**
