### PR TITLE
Create do-you-speak-prestashop-june-2023

### PR DESCRIPTION
**Pull request by l-delin**

### CODE REVIEW

**Comment by l-delin** [comment]
Hellooo 🏋️

The latest _Do you speak PrestaShop?_ article is ready for review, @coffrep @kpodemski :-)  Thanks! 🗞

**Review by coffrep — APPROVED** [review]
Hi @l-delin , I'm approving, great post.

**Review by mflasquin — APPROVED** [review]

**Comment by l-delin** [comment]
Hello, I just realised this was not published for some reason? 😅 I can't find it on the blog @kpodemski

**Comment by coffrep** [comment]
Hi Lea, thanks for catching this, we'll have to investigate, @Krystian
Podemski ***@***.***> comes back tomorrow.

**Comment by kpodemski** [comment]
@l-delin name of the file was without `.md` extension :)

**Comment by l-delin** [comment]
Oh 😅 thanks 
should I make a new PR or can I edit this one? @kpodemski

**Comment by kpodemski** [comment]
@l-delin I fixed it, article is now online :)

**Comment by l-delin** [comment]
thank you so much 🏋️

**Pull request merged**
