### PR TITLE
Upcoming demo September 2022

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | To be published on 31/08/2022
| Fixed ticket? | n/a

### CODE REVIEW

**Comment by leemyongpakvn** [comment]
@kpodemski Missing an **e** character at line 15 :)

**Comment by matks** [comment]
> @kpodemski Missing an **e** character at line 15 :)

Hi @leemyongpakvn you're doing an amazing job on the prestashop project. I see you're motivated and skilled. Do you think you would be interested in going further and maybe join us as a [Committer](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/) ?

If you're interested and want to chat about it, please join us in the prestashop [slack channel](https://www.prestashop-project.org/slack/) 😉

**Review by matks — APPROVED** [review]
@kpodemski All good for me 😄

**Comment by leemyongpakvn** [comment]
@matks Of course, I'm interested in going further in the prestashop project. Become a Committer sounds great, but my time here is not long enough and I'm still in studying phase, so I will consider your invitation next year :)

**Comment by matks** [comment]
> @matks Of course, I'm interested in going further in the prestashop project. Become a Committer sounds great, but my time here is not long enough and I'm still in studying phase, so I will consider your invitation next year :)

See you in 4 months then 😉

**Pull request merged**
