### PR TITLE
Use jekyll serve.

### PR DESCRIPTION
**Pull request by alexsegura**
Easier to get started, it will start a local server and watch for changes. 

Tell me if you think this has issues, otherwise I'll add some details on how to use it.

### CODE REVIEW

**Comment by xBorderie** [comment]
:clap: 

ping @julienbourdeau

**Comment by julienbourdeau** [comment]
I'm waiting for the modifications we talked about on Gitter :)

**Comment by alexsegura** [comment]
It's now ok I think.

**Comment by julienbourdeau** [comment]
Thank you !

**Pull request merged**
