### PR TITLE
Fixed authors array

### PR DESCRIPTION
**Pull request by aleeks**
ping @xBorderie @maximebiloe

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks guys! <3

**Comment by aleeks** [comment]
I don't know if it works :smile:

**Comment by xBorderie** [comment]
It did: yesterday's Core Weekly is now online :)
http://build.prestashop.com/news/coreweekly-week-17-2017/

**Comment by maximebiloe** [comment]
If fixes some errors, but not all of them with the seo plugin. I'll keep searching what's going on...

**Pull request merged**
