### PR TITLE
Add release note 1.7.6.9

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add release note for 1.7.6.9

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
@atomiix My bad I just saw we did a mistake: the file for this release note should have been put in `news/_posts/releases`

**Comment by ttoine** [comment]
is possible to move it in the right folder?

**Comment by atomiix** [comment]
I think so, I'm gonna do a new PR to fix that.

**Comment by atomiix** [comment]
@matks @ttoine here we are: https://github.com/PrestaShop/prestashop.github.io/pull/799

**Pull request merged**
